### PR TITLE
Helm chart: Support API secret management for v1.0.x

### PR DESCRIPTION
**Pull request by outscale-age**
**Is this a bug fix or adding new feature?**

This PR adds a new feature to the Helm chart: the secret used to contain the AK/SK for the API can now be named anything, and can also be created and deployed by the chart if the user requests it.

**What is this PR about? / Why do we need it?**

Sometimes, you want to deploy the CSI driver with all its deps with a single helm install. Sometimes, you also have a naming convention for secrets.

**What testing is done?**

None

### CODE REVIEW

**Review by jerome-jutteau — APPROVED** [review]
LGTM

**Review by outscale-mdr — CHANGES_REQUESTED** [review]
Thank you for this feature, could you add theses new elements in the documentation (docs/helm.md)

**Comment by outscale-age** [comment]
I added the documentation for the new values.

**Review by outscale-mdr — APPROVED** [review]
Thank you for your contribution !

**Pull request merged**
